- name: "Unattended-Install configuration"
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: install unattended-upgrades
      apt: name=unattended-upgrades update_cache=yes

    - name: apply unattended-upgrades config files
      copy: backup=yes src=./config-files/ dest=/etc/apt/apt.conf.d/